modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/DarkRoleplay/Dark-Roleplay-Library/issues" #optional
displayURL="https://dark-roleplay.net/" #optional

#logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java"#optional
authors="Lead Programmer: JTK222" #optional

[[mods]] #mandatory
	modId="drplibrary" #mandatory
	version="1.13.2-0.1.0-SNAPSHOT" #mandatory
	displayName="Dark Roleplay Library" #mandatory
	#updateJSONURL="http://myurl.me/" #optional
	description='''
		This is a long form description of the mod. You can write whatever you want here
		
		Have some lorem ipsum.
		
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis lacinia magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sagittis luctus odio eu tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque volutpat ligula eget lacus auctor sagittis. In hac habitasse platea dictumst. Nunc gravida elit vitae sem vehicula efficitur. Donec mattis ipsum et arcu lobortis, eleifend sagittis sem rutrum. Cras pharetra quam eget posuere fermentum. Sed id tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
	'''
[[dependencies.drplibrary]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"